version: '3.8'  # Specify Docker Compose file format version

services:
  mysql:
    image: mysql:latest  # Use the latest MySQL image
    container_name: mesplus-mysql  # Optional container name
    restart: always  # Restart the container if it stops
    ports:
      - "3306:3306"  # Map host port 3306 to container port 3306
    environment:
      MYSQL_ROOT_PASSWORD: pass  # Set the root password
      MYSQL_DATABASE: mydatabase  # Create a database named "my_database"
    volumes:
      - mysql-data:/var/lib/mysql  # Create a volume to persist data


volumes:
  mysql-data:  # Define the volume
